FROM php:7.4-apache

WORKDIR /var/www/html
COPY index.php /var/www/html/
COPY conexao.php /var/www/html/

RUN apt-get update && apt-get install   \
        libfreetype6-dev    \
        libjpeg62